### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'title'

### ISSUE THREAD

**Issue by fradexnox** [rwk506/HessDiagram#1]
When I use the function without a colormap, it works, but when I try choosing a color, I got that error. It also appears when I run the example.

**Comment by rwk506** [comment]
Hi, thanks for letting me know. Can you send me the specifications of your function call as well as the system/version you are running this on? (As a sanity check, please confirm that you have forked the repository and have all the necessary files present in the directory you are calling from).

**Comment by rwk506** [comment]
I have updated a few things that possibly were the cause of the issue you were having. Please let me know if you still have problems.

**Comment by fradexnox** [comment]
Hi!, thanks, it worked.
